version: "3"

networks:
  myapp:
    external: true

services:
  user-app:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DB_URL=postgres://root:root@app-db:5432/app-db?sslmode=disable
      - PORT=8001
    networks:
      - myapp