version: "3"

networks:
  myapp:
    external: true

services:
  app-db:
    image: postgres:latest
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app-db
      APP_DB_USER: docker
      APP_DB_PASS: docker
    healthcheck:
      test: PGPASSWORD='root' psql -U root --command='SELECT 1' --dbname=app-db
      interval: 1s
      timeout: 2s
      retries: 5
    networks:
      - myapp